### ISSUE TITLE
RGB is being ignored in `sample()`

### ISSUE THREAD

**Issue by eleweek** [darosh/colorgram-js#1]
Thanks for the library, it works great for computing a dominant color in the image. The results are great for our purposes. 

However, I noticed that RGB components are being ignored and only H, S and M are taking into account. 
```
 ((img.data[i] & mask) << shiftR) +
 ((img.data[i + 1] & mask) << shiftG) +
((img.data[i + 2] & mask << shiftB));
```

This evaluates to `0`, because `shiftR`. `shiftG` and `shiftB` are all negative:

```
var shiftR:number = -lowBits + 2 * topBits;
var shiftG:number = -lowBits + topBits;
var shiftB:number = -lowBits;
```

Just check `42 << -1` or `42 >> -1`

There are two ways to fix this:
1) Either get rid of negative bitshifts. This leads to different palettes with more similar colors.
2) Drop RGB from the space entirely. This should bring the memory consumption to 1KB, while keeping the results the same. 

I'll let you decide what do with this.

**Comment by darosh** [comment]
@eleweek Thanks a lot! I dropped the RGB completely.
