### ISSUE TITLE
The lib is using 256 KB of memory instead of 64 KB (as claimed)

### ISSUE THREAD

**Issue by eleweek** [darosh/colorgram-js#2]
I outlined bigger problem in #1, but a quick fix to reduce RAM consumption for the lib is to:

```
// Skipping S from HSL
// var cubes = sides * sides * sides * sides * sides * sides * sides;
var cubes:number = sides * sides * sides * sides * sides * sides * sides;
```

It looks like a typo - there is one extra `* sides`.

Again, thanks for the library - it works great, but some memory can be saved!

**Comment by darosh** [comment]
Oh, yes it is a 192 KB heavy typo. Thanks!

**Comment by eleweek** [comment]
It's also easily fixable by removing one of the sides. The lib is allocating 256 KB but using only 64KB.
