### ISSUE TITLE
Question : Can we use directly on Image

### ISSUE THREAD

**Issue by ramchandracheke** [darosh/colorgram-js#8]
Hi,
Thanks for the great work! 

# Extract 6 colors from an image.
colors = colorgram.extract('img20_500.png', 6)
colors

Actually, My image is already in Numpy array, and I don't want to read it once again. Is there a way to direct process the image that is already in the Ndarray(RGB) format.

Thanks,
Ram

**Comment by darosh** [comment]
Hi @ramchandracheke This is JavaScript library. I assume you want to use Python? (Which I do not know much about.) There is a port to Python available here: https://github.com/obskyr/colorgram.py (Which I do not know much about as well. 😊) I guess you came here from there and you wanted to ask there?

**Comment by ramchandracheke** [comment]
Yeah . I am using it in Python ! Thanks for quick reply.. Really appreciate it. 

Kind regards,
Ram

**Comment by ramchandracheke** [comment]
Hi @darosh ,

I was trying to install it in my local machine and I ran into a problem. Please refer the attached image.
 Could you please tell me a few steps to use Javascript Version as I am finding it difficult to make it work locally. Thanks a million!

![image](https://user-images.githubusercontent.com/46112629/90985306-010f4880-e573-11ea-80a3-e00a3de5ea2f.png)
